name: lats

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

addons:
- name: bosh-dns
  include:
    stemcell:
    - os: ubuntu-trusty
  jobs:
  - name: bosh-dns
    release: bosh-dns
    properties:
      api:
        client:
          tls:
            ca: ((dns_api_tls_ca.certificate))
            certificate: ((dns_api_client_tls.certificate))
            private_key: ((dns_api_client_tls.private_key))
        server:
          tls:
            ca: ((dns_api_tls_ca.certificate))
            certificate: ((dns_api_server_tls.certificate))
            private_key: ((dns_api_server_tls.private_key))
      cache:
        enabled: true
      health:
        enabled: true
        server:
          tls:
            ca: ((dns_healthcheck_tls_ca.certificate))
            certificate: ((dns_healthcheck_server_tls.certificate))
            private_key: ((dns_healthcheck_server_tls.private_key))
        client:
          tls:
            ca: ((dns_healthcheck_tls_ca.certificate))
            certificate: ((dns_healthcheck_client_tls.certificate))
            private_key: ((dns_healthcheck_client_tls.private_key))

releases:
- name: logging-acceptance-tests
  version: latest
- name: bosh-dns
  sha1: bb7f1cf29c4186fdba4a049fb6feb5638227d9a4
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=1.6.0
  version: 1.6.0
- name: loggregator
  version: latest

instance_groups:
- name: lats
  azs:
  - z1
  instances: 1
  vm_type: minimal
  stemcell: default
  lifecycle: errand
  networks:
  - name: default
  jobs:
  - name: lats
    release: logging-acceptance-tests
    consumes:
      trafficcontroller: {from: trafficcontroller, deployment: loggregator}
      reverse_log_proxy: {from: reverse_log_proxy, deployment: loggregator}
    properties:
      traffic_controller:
        disable_access_control: true
  - name: metron_agent
    release: loggregator
    consumes:
      doppler: {from: doppler, deployment: loggregator}
    properties: &metron_agent_properties
      doppler:
        addr: ~
      metron_agent:
        disable_udp: false
        deployment: loggregator
        bosh_dns: true
      loggregator:
        tls:
          ca_cert: "((loggregator_metron.ca))"
          metron:
            cert: "((loggregator_metron.certificate))"
            key: "((loggregator_metron.private_key))"

variables:
- name: loggregator_metron
  type: certificate
  options:
    ca: loggregator_ca
    common_name: metron
    extended_key_usage:
    - client_auth
    - server_auth
- name: dns_api_tls_ca
  options:
    common_name: dnsApiTlsCa
    is_ca: true
  type: certificate
- name: dns_api_client_tls
  options:
    ca: dns_api_tls_ca
    common_name: api.bosh-dns
    extended_key_usage:
    - client_auth
  type: certificate
- name: dns_api_server_tls
  options:
    ca: dns_api_tls_ca
    common_name: api.bosh-dns
    extended_key_usage:
    - server_auth
  type: certificate
- name: dns_healthcheck_tls_ca
  type: certificate
  options:
    common_name: dnsHealthCheckTlsCa
    is_ca: true
- name: dns_healthcheck_server_tls
  type: certificate
  options:
    ca: dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - server_auth
- name: dns_healthcheck_client_tls
  type: certificate
  options:
    ca: dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - client_auth

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
