name: lats

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

releases:
- name: logging-acceptance-tests
  version: latest
- name: loggregator
  version: latest
- name: loggregator-agent
  version: latest
- name: bpm
  version: latest

addons:
- name: bpm
  include:
    stemcell:
    - os: ubuntu-trusty
    - os: ubuntu-xenial
  jobs:
  - name: bpm
    release: bpm


instance_groups:
- name: lats
  azs:
  - z1
  instances: 1
  vm_type: minimal
  stemcell: default
  lifecycle: errand
  networks:
  - name: default
  jobs:
  - name: lats
    release: logging-acceptance-tests
    consumes:
      trafficcontroller: {from: trafficcontroller, deployment: loggregator}
      reverse_log_proxy: {from: reverse_log_proxy, deployment: loggregator}
    properties:
      traffic_controller:
        disable_access_control: true
  - name: loggregator_agent
    release: loggregator-agent
    consumes:
      doppler: {from: doppler, deployment: loggregator}
    properties: &agent_properties
      doppler:
        addr: ~
      disable_udp: false
      deployment: loggregator
      bosh_dns: true
      loggregator:
        tls:
          ca_cert: "((loggregator_agent.ca))"
          agent:
            cert: "((loggregator_agent.certificate))"
            key: "((loggregator_agent.private_key))"

variables:
- name: loggregator_agent
  type: certificate
  options:
    ca: loggregator_ca
    common_name: agent
    alternative_names:
    - metron
    extended_key_usage:
    - client_auth
    - server_auth
- name: dns_api_tls_ca
  options:
    common_name: dnsApiTlsCa
    is_ca: true
  type: certificate
- name: dns_api_client_tls
  options:
    ca: dns_api_tls_ca
    common_name: api.bosh-dns
    extended_key_usage:
    - client_auth
  type: certificate
- name: dns_api_server_tls
  options:
    ca: dns_api_tls_ca
    common_name: api.bosh-dns
    extended_key_usage:
    - server_auth
  type: certificate
- name: dns_healthcheck_tls_ca
  type: certificate
  options:
    common_name: dnsHealthCheckTlsCa
    is_ca: true
- name: dns_healthcheck_server_tls
  type: certificate
  options:
    ca: dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - server_auth
- name: dns_healthcheck_client_tls
  type: certificate
  options:
    ca: dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - client_auth

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
