name: noop-syslog-server

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

releases:
- name: bpm
  version: latest
- name: logging-acceptance-tests
  version: latest

addons:
- name: bpm
  include:
    stemcell:
    - os: ubuntu-xenial
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: noop-syslog-server
  azs:
  - z1
  instances: 1
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: noop-syslog-server
    release: logging-acceptance-tests
    properties:
      ssl:
        cert: "((loggregator_agent.certificate))"
        key: "((loggregator_agent.private_key))"

variables:
- name: loggregator_ca
  type: certificate
  options:
    common_name: loggregatorCA
    is_ca: true
- name: loggregator_agent
  type: certificate
  options:
    ca: loggregator_ca
    common_name: agent
    alternative_names:
    - metron
    - agent
    - localhost
    - 127.0.0.1
    - ip6-localhost
    extended_key_usage:
    - client_auth
    - server_auth

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
